### PR TITLE
Solve build issues with ibm xlf

### PR DESCRIPTION
**Pull request by friedc**
**Description**

I configure  lapack-3.10.1 with the following options:

```
cmake -H. -Bobjdir -DCMAKE_C_COMPILER=gcc -DCMAKE_Fortran_COMPILER=xlf -DCMAKE_INSTALL_PREFIX=/run_dir/3rd-party -DBUILD_INDEX64=ON -DBUILD_SINGLE=OFF -DBUILD_COMPLEX=OFF -DCBLAS=OFF -DLAPACKE=OFF
```

cmake then fails with the following message:

```
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Failed to compile
-- Verifying Fortran/C Compiler Compatibility
CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FortranCInterface.cmake:309 (message):
  No FortranCInterface mangling known for VerifyFortran
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FortranCInterface/Verify/CMakeLists.txt:16 (FortranCInterface_HEADER)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Verifying Fortran/C Compiler Compatibility - Failed
...
    [100%] Linking C executable VerifyFortranC
    /usr/bin/cmake -E cmake_link_script CMakeFiles/VerifyFortranC.dir/link.txt --verbose=1
    /usr/bin/gcc  -DWeirdNEC -DLAPACK_ILP64 -DHAVE_LAPACK_CONFIG_H -O3 -DNDEBUG   CMakeFiles/VerifyFortranC.dir/main.c.o CMakeFiles/VerifyFortranC.dir/VerifyC.c.o  -o VerifyFortranC   -L/opt/ibm/xlsmp/5.1.1/lib  -L/opt/ibm/xlmass/9.1.1/lib  -L/opt/ibm/xlf/16.1.1/lib  libVerifyFortran.a -lxlf90 -lxlopt -lxlomp_ser -lxl -lxlfmath -ldl -lrt -lpthread -lm 
    /usr/bin/ld: CMakeFiles/VerifyFortranC.dir/main.c.o: in function `main':
    main.c:(.text.startup+0x1c): undefined reference to `VerifyFortran'
...
Call Stack (most recent call first):
  LAPACKE/CMakeLists.txt:4 (FortranCInterface_VERIFY)
```

Here I have:
```
# cmake --version
cmake version 3.16.3
...
# gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
...
# xlf -qversion
IBM XL Fortran for Linux, V16.1.1 (Community Edition)
Version: 16.01.0001.0003
...
```

You will notice that I do not want to build LAPACKE, but it still breaks the build. This is addressed by commit 8d3ae005a3587e3e271cf80871d708d6b38c7fff. I can now get a bit further with the build.

```
cd objdir && /usr/bin/make VERBOSE=1
```

yields

```
[  1%] Building Fortran object BLAS/SRC/CMakeFiles/blas64.dir/xerbla_array.f.o
cd /run_dir/3rd-party/lapack/objdir/BLAS/SRC && /opt/ibm/xlf/16.1.1/bin/xlf   -qthreaded -qhalt=e -qrecur -qnosave -qstrict -fdefault-integer-8 -O   -c /run_dir/3rd-party/lapack/BLAS/SRC/xerbla_array.f -o CMakeFiles/blas64.dir/xerbla_array.f.o
COMMAND LINE  1520-065 (W) The XLF77(PERSISTENT) option stores entities in static storage.  This may affect the thread safety of your code.
"/run_dir/3rd-party/lapack/BLAS/SRC/xerbla_array.f", line 108.16: 1515-009 (E) Null literal string is not permitted.  A single blank is assumed.
** xerbla_array   === End of Compilation 1 ===
1501-511  Compilation failed for file xerbla_array.f.
```

The failed compilations is addressed by commit 7939cb1b4d977da37a90c3b515f4ce4c3fe82435. Now the build completes successfully.

**Checklist**

- [ ] The documentation has been updated.
- [x] If the PR solves a specific issue, it is set to be closed on merge.

### CODE REVIEW

**Review by weslleyspereira — DISMISSED** [review]

**Comment by weslleyspereira** [comment]
There is a conflict we should solve before merge. It is simple. @friedc, may I just solve it and then merge your branch? Thanks.

**Comment by friedc** [comment]
> There is a conflict we should solve before merge. It is simple. @friedc, may I just solve it and then merge your branch? Thanks.

Sorry, I didn't see the merge conflict before. I will try to solve it myself and report back if I am not able to.

**Review by langou — APPROVED** [review]

File: LAPACKE/CMakeLists.txt [hunk 1]
```diff
@@ -14,11 +19,6 @@ endif()
 add_subdirectory(include)
 
 
-if(NOT LAPACKE)
-    return()
-endif()
-
-
```
[the remark this answers is not in the document]
Comment (christoph-conrads) [reply LAPACKE/CMakeLists.txt:21]: > I am just unsure whether this specific displacement of code could cause problems using other configurations with cmake.

The code was specifically placed this way for #632.

[the remark this answers is not in the document]
Comment (weslleyspereira) [reply LAPACKE/CMakeLists.txt:21]: I agree with your suggestion, @friedc. I see no need to check the compatibility between Fortran and C compilers if we are just installing a C header file.

```diff
diff --git a/LAPACKE/CMakeLists.txt b/LAPACKE/CMakeLists.txt
index bbe84cbb2..ba105dfb2 100644
--- a/LAPACKE/CMakeLists.txt
+++ b/LAPACKE/CMakeLists.txt
@@ -1,12 +1,5 @@
-if(NOT LAPACKE)
-    return()
-endif()
-
-
 # Create a header file lapacke_mangling.h for the routines called in my C programs
 include(FortranCInterface)
-## Ensure that the fortran compiler and c compiler specified are compatible
-FortranCInterface_VERIFY()
 FortranCInterface_HEADER(${LAPACK_BINARY_DIR}/include/lapacke_mangling.h
   MACRO_NAMESPACE "LAPACK_"
   SYMBOL_NAMESPACE "LAPACK_")
@@ -18,6 +11,12 @@ endif()
 
 add_subdirectory(include)
 
+if(NOT LAPACKE)
+    return()
+endif()
+
+## Ensure that the fortran compiler and c compiler specified are compatible
+FortranCInterface_VERIFY()
 
 message(STATUS "LAPACKE enabled")
 enable_language(C)
 ```
 
This should be the patch, right? If so, I can propose a PR with this change to close #692.

[the remark this answers is not in the document]
Comment (friedc) [reply LAPACKE/CMakeLists.txt:21]: Acutally when trying

```
cmake -Bobjdir -DCMAKE_C_COMPILER=gcc -DCMAKE_Fortran_COMPILER=xlf -DBUILD_INDEX64=ON -DLAPACKE=ON
```

now it works without a problem

```
...
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
-- Verifying Fortran/C Compiler Compatibility
-- Verifying Fortran/C Compiler Compatibility - Success
-- LAPACKE enabled
```

It would be easier to just revert 8d3ae005a3587e3e271cf80871d708d6b38c7fff since no one else is having a problem with it.
