### ISSUE TITLE
Link errors in lapacke 3.8.0 after upgrade from 3.6.1 on fedora

### ISSUE THREAD

**Issue by txsol** [Reference-LAPACK/lapack#241]
I just performed a "dnf upgrade" on Fedora 27 an was upgraded to BLAS/LAPACK 3.8.0

Code I had been working on just prior to the upgrade/reboot now has link errors.
I moved the same code to a machine that has BLAS/LAPACK 3.6.1 and it compiles and links correctly.

I get this error even when no calls to LAPACK are made from my code. To demonstrate this I ran the following two lines:

$ echo "int main(void) { return 0; }" > test.c
$ gcc -o test test.c -lm -llapack -lblas -llapacke

/usr/lib/gcc/x86_64-redhat-linux/7/../../../../lib64/liblapacke.so: undefined reference to LAPACKE_dsytrf_aa_work

/usr/lib/gcc/x86_64-redhat-linux/7/../../../../lib64/liblapacke.so: undefined reference to LAPACKE_ssytrf_aa_work

collect2: error: ld returned 1 exit status

$ ll /usr/lib64/libblas*
lrwxrwxrwx. 1 root root     16 Jan  4 13:39 /usr/lib64/libblas.so -> libblas.so.3.8.0
lrwxrwxrwx. 1 root root     16 Jan  4 13:39 /usr/lib64/libblas.so.3 -> libblas.so.3.8.0
lrwxrwxrwx. 1 root root     16 Jan  4 13:39 /usr/lib64/libblas.so.3.8 -> libblas.so.3.8.0
-rwxr-xr-x. 1 root root 352544 Jan  4 13:39 /usr/lib64/libblas.so.3.8.0

$ ll /usr/lib64/liblapack*
lrwxrwxrwx. 1 root root      19 Jan  4 13:39 /usr/lib64/liblapacke.so -> liblapacke.so.3.8.0
lrwxrwxrwx. 1 root root      19 Jan  4 13:39 /usr/lib64/liblapacke.so.3 -> liblapacke.so.3.8.0
lrwxrwxrwx. 1 root root      19 Jan  4 13:39 /usr/lib64/liblapacke.so.3.8 -> liblapacke.so.3.8.0
-rwxr-xr-x. 1 root root 2763640 Jan  4 13:39 /usr/lib64/liblapacke.so.3.8.0
lrwxrwxrwx. 1 root root      18 Jan  4 13:39 /usr/lib64/liblapack.so -> liblapack.so.3.8.0
lrwxrwxrwx. 1 root root      18 Jan  4 13:39 /usr/lib64/liblapack.so.3 -> liblapack.so.3.8.0
lrwxrwxrwx. 1 root root      18 Jan  4 13:39 /usr/lib64/liblapack.so.3.8 -> liblapack.so.3.8.0
-rwxr-xr-x. 1 root root 7036144 Jan  4 13:39 /usr/lib64/liblapack.so.3.8.0

Switching between lapack 3.7.1 and 3.8.0
The following steps are reproducible:

1.  cat /etc/redhat-release
2.  rpm -q lapack
3.  echo "int main(void) { return 0; }" > test.c
4.  gcc -o test test.c -lm -llapack -lblas -llapacke
5.  sudo dnf downgrade blas lapack
6.  rpm -q lapack
7.  gcc -o test test.c -lm -llapack -lblas -llapacke
8.  sudo dnf distro-sync blas lapack
9.  rpm -q lapack
10. gcc -o test test.c -lm -llapack -lblas -llapacke

Step 1:   Fedora release 27 (Twenty Seven)
Step 2:   lapack-3.8.0-4.fc27.x86_64
Step 4:   Link errors
Step 6:   lapack-3.7.1-5.fc27.x86_64
Step 7:   no link errors
Step 9:   lapack-3.8.0-4.fc27.x86_64
Step 10: Link errors

**Comment by huijwliu** [comment]
The file, lapack-3.8.0/LAPACKE/src/Makefile, missed two object files:

lapacke_dsytrf_aa_work.o and lapacke_ssytrf_aa_work.o, which should be included in OBJ_A.

**Comment by martin-frbg** [comment]
You can get the changes from #208, or just copy the LAPACKE Makefile from the current git
